# Generated by Django 5.0.1 on 2024-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_salud_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id_afp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
