# Generated by Django 5.0.1 on 2024-01-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_afp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
                ('Area_Desempeno', models.CharField(blank=True, max_length=50, null=True)),
                ('Sueldo_Base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha_Ingreso', models.DateField(blank=True, null=True)),
                ('Dias_Vacaciones', models.IntegerField(blank=True, null=True)),
                ('Bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Comisiones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Fecha_Contrato', models.DateField(blank=True, null=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Clave_Usuario', models.CharField(max_length=50)),
                ('Especializacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Area_A_Cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.afp')),
                ('id_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.salud')),
            ],
        ),
    ]
