# Generated by Django 5.0.1 on 2024-01-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id_p_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('encargado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRequisicion',
            fields=[
                ('id_requisicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('productos', models.TextField()),
                ('entregado_por', models.CharField(max_length=150)),
                ('recibido_por', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.bodega')),
            ],
        ),
    ]
