# Generated by Django 5.0.1 on 2024-01-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_liquidacionsueldo_ordenproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(max_length=300)),
                ('stock', models.IntegerField()),
                ('posicion', models.CharField(max_length=10)),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_Comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FactorProducto',
            fields=[
                ('id_factor_prod', models.AutoField(primary_key=True, serialize=False)),
                ('factor_venta', models.FloatField()),
                ('nombre_producto', models.CharField(max_length=20)),
                ('precio_unitario', models.IntegerField()),
                ('fecha_modificacion', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.producto')),
            ],
        ),
    ]
