# Generated by Django 5.0.1 on 2024-01-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_producto_ordencompra_factorproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run_cliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id_n_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('importe', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.producto')),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.cliente')),
                ('rut_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('id_cliente', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=20)),
                ('cantidad_producto', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('IVA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_n_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.notaventa')),
            ],
        ),
    ]
