# Generated by Django 4.2.1 on 2024-01-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_cliente_notaventa_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorproducto',
            name='precio_final',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
